/*
 * Turns editor state into the text of user{N}.css, where {N} is
 * state.fileNumber (see js/state.js and PCE_FILE_NUMBER_NOTE in
 * js/incGenerator.js).
 */

function pceFormatControlValue(control, rawValue) {
  if (control.type === 'range') return `${rawValue}${control.unit || ''}`;
  return rawValue;
}

function pceIconDataUri(templateKey, color) {
  const svg = PCE_ICON_SVG_TEMPLATES[templateKey](color);
  return `data:image/svg+xml,${encodeURIComponent(svg)}`;
}

function pceGenerateUserCss(state) {
  const lines = [];

  const fileNumber = state.fileNumber || 3;
  lines.push('/*');
  lines.push(` * user${fileNumber}.css`);
  lines.push(' * Generated by the PaperCut Custom Web UI Editor.');
  lines.push(' * Place this file in [app-path]/server/custom/web/ on your PaperCut server');
  lines.push(' * (UTF-8 encoding). It is included as an overriding stylesheet on top of');
  lines.push(" * PaperCut's built-in theme.");
  lines.push(' *');
  lines.push(` * ${PCE_FILE_NUMBER_NOTE}`);
  lines.push(' */');
  lines.push('');

  const varControls = [];
  for (const group of Object.values(PCE_SCHEMA)) {
    for (const c of pceGroupControls(group)) {
      if (c.cssVar) varControls.push(c);
    }
  }
  if (varControls.length) {
    lines.push(':root {');
    for (const c of varControls) {
      lines.push(`  ${c.cssVar}: ${state.controls[c.id]}; /* ${c.label} */`);
    }
    lines.push('}');
    lines.push('');
  }

  for (const group of Object.values(PCE_SCHEMA)) {
    const all = pceGroupControls(group);
    const ruleControls = all.filter(c => c.rules && c.rules.length);
    const iconControls = all.filter(c => c.iconRules && c.iconRules.length);
    if (!ruleControls.length && !iconControls.length) continue;
    lines.push(`/* ${group.label} */`);
    for (const c of ruleControls) {
      const value = pceFormatControlValue(c, state.controls[c.id]);
      for (const rule of c.rules) {
        lines.push(`${rule.selector} {`);
        lines.push(`  ${rule.prop}: ${value}${rule.important ? ' !important' : ''};`);
        lines.push('}');
      }
    }
    for (const c of iconControls) {
      const color = state.controls[c.id];
      for (const rule of c.iconRules) {
        lines.push(`${rule.selector} {`);
        lines.push(`  background-image: url("${pceIconDataUri(rule.svg, color)}");`);
        lines.push('  background-position: center;');
        lines.push('  background-repeat: no-repeat;');
        lines.push(`  background-size: ${rule.size};`);
        lines.push('}');
      }
    }
    lines.push('');
  }

  if (state.advancedCss && state.advancedCss.trim()) {
    lines.push('/* ------------------------------------------------------------------- */');
    lines.push('/* Advanced: custom CSS, appended verbatim                              */');
    lines.push('/* ------------------------------------------------------------------- */');
    lines.push(state.advancedCss.trim());
    lines.push('');
  }

  return lines.join('\n');
}

/** Escapes a string so it can't prematurely close a <style> element it's embedded in. */
function pceEscapeStyleClose(css) {
  return css.replace(/<\/style/gi, '<\\/style');
}
